repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-ast
      - id: double-quote-string-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.0.2
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--skip-string-normalization]

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 2.0.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-annotations
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-pie
          - flake8-quotes
          - flake8-simplify
          - flake8-tidy-imports
          - flake8-use-fstring
